### ISSUE TITLE
Add local DA Cert verification support

### ISSUE THREAD

**Issue by teddyknox** [Layr-Labs/eigenda-proxy#16]
Doing local DA cert verification means:
1. Calling [VerifyBlob()](https://github.com/Layr-Labs/eigenda/blob/fa5866c7de5f42e24def9b902f0dd19e63c0a9a6/contracts/src/libraries/EigenDARollupUtils.sol#L33) on some singleton deployment of the library so that the client can be confident that the disperser is not lying when it reports the blob as confirmed.
2. Ensuring that the block that finalized the blob is indeed finalized.
  2a. There is a sub-step here of verifying the L1 block that the disperser claims the blob's batch was confirmed in. Otherwise the finalization claim is also trusted. I'm not sure how to do this except filtering on transactions in the claimed block, looking for batch confirmation transactions, and then positively identifying the batch header hash in hand with the one in the L1 block. If this is too time-consuming this step can be decoupled from this task as a further TODO.

**Comment by epociask** [comment]
Since this logic isn't deploy under a singelton we'll have to reproduce the library verification code within golang. This will require replicating the following invariant checks:
A. The blob header hash stored on-chain is equivalent to the one generated from the disperser returned batch metadata: https://github.com/Layr-Labs/eigenda/blob/2ade91370441ebfefe717865f64a4ace11241639/contracts/src/libraries/EigenDARollupUtils.sol#L38-L42 
B. The inclusion proof can be merkalized to generate the batch header root stored on-chain: https://github.com/Layr-Labs/eigenda/blob/2ade91370441ebfefe717865f64a4ace11241639/contracts/src/libraries/EigenDARollupUtils.sol#L44-L52 
C. All quorum are adequately defined
